import fs from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {Workbook,SpreadsheetFile} from "@oai/artifact-tool";
const data=JSON.parse(await fs.readFile(new URL("../schemas/book_vii_controls.json",import.meta.url),"utf8"));
const parse=(t,n)=>t.split("\n").filter(x=>x.startsWith("|")&&!x.includes("---")).map(x=>x.split("|").slice(1,-1).map(v=>v.trim())).filter(x=>x.length===n);
const v=parse(await fs.readFile(new URL("../planning/BOOK_V_RECONCILIATION_REGISTER.md",import.meta.url),"utf8"),5);
const vi=parse(await fs.readFile(new URL("../planning/BOOK_VI_RECONCILIATION_REGISTER.md",import.meta.url),"utf8"),5);
const wb=Workbook.create();const names=["Summary","Controls","Decision Classes","Authority Matrix","Book V Reconciliation","Book VI Reconciliation"];const ss=names.map(n=>wb.worksheets.add(n));for(const s of ss)s.showGridLines=false;
const [summary,controls,classes,authority,bv,bvi]=ss;const navy="#17365D",blue="#D9EAF7",ink="#1F2937",line="#D7DEE8",amber="#FFF2CC";
function tab(s,h,r,w,n){s.getRangeByIndexes(0,0,r.length+1,h.length).values=[h,...r];let e=String.fromCharCode(64+h.length);s.getRange(`A1:${e}1`).format={fill:navy,font:{bold:true,color:"#FFFFFF"},wrapText:true};s.getRange(`A2:${e}${r.length+1}`).format={font:{size:9,color:ink},wrapText:true};s.getRange(`A1:${e}${r.length+1}`).format.borders={preset:"insideHorizontal",style:"thin",color:line};w.forEach((x,i)=>s.getRange(`${String.fromCharCode(65+i)}:${String.fromCharCode(65+i)}`).format.columnWidth=x);s.freezePanes.freezeRows(1);s.tables.add(`A1:${e}${r.length+1}`,true,n).style="TableStyleMedium2";}
summary.getRange("A1:F2").merge();summary.getRange("A1").values=[["HAL Book VII — Governance and Stewardship"]];summary.getRange("A1:F2").format={fill:navy,font:{bold:true,color:"#FFFFFF",size:18}};
summary.getRange("A4:B11").values=[["Metric","Value"],["Status","Certified Final"],["Certified","YES"],["Chapters",12],["Controls",null],["Templates",8],["Closed Book V items",null],["Closed Book VI items",null]];
summary.getRange("B8").formulas=[["=COUNTA(Controls!A2:A97)"]];summary.getRange("B10").formulas=[["=COUNTA('Book V Reconciliation'!A2:A9)"]];summary.getRange("B11").formulas=[["=COUNTA('Book VI Reconciliation'!A2:A9)"]];
summary.getRange("A4:B4").format={fill:blue,font:{bold:true,color:navy}};summary.getRange("A13:F14").merge();summary.getRange("A13").values=[["CERTIFIED FINAL: Books V and VI are final; all sixteen reconciliation items are closed; no constitutional conflict or Owner-required decision remains."]];summary.getRange("A13:F14").format={fill:"#E2F0D9",font:{bold:true,color:"#375623"},wrapText:true};summary.getRange("A:A").format.columnWidth=31;summary.getRange("B:F").format.columnWidth=18;
const cr=data.controls.map(c=>[c.control_id,c.chapter,c.category,c.title,c.requirement,c.applicability,c.responsible_role,c.enforcement,c.evidence,c.severity,c.exception_authority,c.source,c.automation]);
tab(controls,["Control ID","Chapter","Category","Title","Requirement","Applicability","Role","Enforcement","Evidence","Severity","Exception Authority","Source","Automation"],cr,[17,10,12,30,70,27,25,38,30,12,24,60,34],"ControlsTable");
tab(classes,["Decision class","Controlling authority","Owner required","Primary record"],[
["Administrative governance","Charter-designated authority","No","Governance Decision Object"],["Operational","Book V authority","No, unless Owner-reserved matter","Operational decision/incident record"],["Engineering policy","Book III authority","No","Policy Change Record"],["Architecture","Book II Architecture Authority","No","Architecture Decision Record"],["Security/privacy/trust","Book VI authority","No, unless Treaty/Owner matter","Security/Privacy/Trust Decision"],["Certification","Book VIII Certification Authority","No","Certification Decision"],["New capability class","Owner","Yes","Owner Approval Record"],["Treaty approval/material change","Owner","Yes","Treaty Decision Record"],["Constitutional amendment/succession","Owner or constitutional process","Yes","Constitutional Change/Succession Record"]
],[32,48,28,40],"DecisionClassTable");
tab(authority,["Function","Proposer","Reviewers","Approver","Recorder","Executor","Appeal/oversight"],[
["Constitutional amendment","Authorized sponsor","Constitutional, compatibility, assurance","Owner","Constitutional Archivist","Amendment Program Lead","Constitutional process"],["Architecture","Technical sponsor","Architecture/security/privacy/assurance","Architecture Authority","Governance Recorder","Component/platform owners","Architecture governance"],["New capability class","Capability sponsor","Architecture/security/privacy/verification","Owner","Capability Steward","Capability owners after certification","Owner reconsideration"],["Treaty","Treaty sponsor","Trust/security/privacy/Firewall/verification","Owner","Treaty Steward","Treaty Manager/Firewall","Owner reconsideration"],["Certification","Target owner","Independent verification/domain reviewers","Certification Authority","Evidence Custodian","Runtime/release authorities","Independent Appeal Authority"],["Emergency","Incident or emergency lead","As available; retrospective mandatory","Declared Emergency Authority","Incident Recorder","Authorized responders","Retrospective governance review"]
],[34,30,50,34,30,36,38],"AuthorityMatrixTable");
tab(bv,v[0],v.slice(1),[15,42,48,58,40],"BookVReconciliationTable");tab(bvi,vi[0],vi.slice(1),[15,42,48,58,40],"BookVIReconciliationTable");
const out=await SpreadsheetFile.exportXlsx(wb);await out.save(fileURLToPath(new URL("../deliverables/HAL_BOOK_VII_GOVERNANCE_CONTROL_CATALOG.xlsx",import.meta.url)));
const pd=new URL("../tmp/workbook-previews/",import.meta.url);await fs.mkdir(pd,{recursive:true});for(const [n,r] of [["Summary","A1:F14"],["Controls","A1:M10"],["Decision Classes","A1:D10"],["Authority Matrix","A1:G7"],["Book V Reconciliation","A1:E9"],["Book VI Reconciliation","A1:E9"]]){const im=await wb.render({sheetName:n,range:r,scale:1,format:"png"});await fs.writeFile(fileURLToPath(new URL(n.toLowerCase().replaceAll(" ","_")+".png",pd)),new Uint8Array(await im.arrayBuffer()));}
const inspect=await wb.inspect({kind:"sheet,table",maxChars:9000,tableMaxRows:5,tableMaxCols:13,tableMaxCellChars:120});await fs.writeFile(fileURLToPath(new URL("../tmp/workbook-inspect.ndjson",import.meta.url)),inspect.ndjson);const err=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:200},summary:"formula error scan"});await fs.writeFile(fileURLToPath(new URL("../tmp/workbook-formula-errors.ndjson",import.meta.url)),err.ndjson);
console.log(JSON.stringify({sheets:6,controls:cr.length,bookV:v.length-1,bookVI:vi.length-1,status:"CERTIFIED_FINAL"}));
